/**
 * This code was generated by the Kepler Codegen tool.
 * 
 * It is provided as a starting template and can be modified.
 * 
 * @generated by GenerateModuleH.js
 */

#include "generated/MkvDemuxModuleSpec.h"

namespace MkvDemuxModuleTurboModule {

class MkvDemuxModule : public MkvDemuxModuleSpec {
public:
  MkvDemuxModule();
  ~MkvDemuxModule() noexcept;

  double getMajorVersion() override;
  double getMinorVersion() override;
  double getPatchVersion() override;
  std::string parseInitSegment(com::amazon::kepler::turbomodule::ArrayBuffer headerBytes) override;
  std::string findClusters(com::amazon::kepler::turbomodule::ArrayBuffer chunk, double baseOffset) override;
  double openRemuxSession(std::string codecId, com::amazon::kepler::turbomodule::ArrayBuffer codecPrivate, double trackNumber, double param1, double param2, double timestampScale, double videoDefaultDurationNs) override;
  com::amazon::kepler::turbomodule::ArrayBuffer remuxChunk(double sessionId, com::amazon::kepler::turbomodule::ArrayBuffer chunk, double baseOffset) override;
  void closeRemuxSession(double sessionId) override;
  std::string extractTextCues(com::amazon::kepler::turbomodule::ArrayBuffer chunk, double trackNumber, bool isAss) override;
};

} // namespace MkvDemuxModuleTurboModule
